### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by iatsdotfatr** [hoka-hoka/task_1#4]
Информацию по установке написать как в слайдере, ссылку на демо также давать из этого ридми, пусть будет одна ссылка на навигационную страницу, откуда можно будет перейти на другие.

**Comment by hoka-hoka** [comment]
Добавил ссылку на демонстрационную страницу. Страница входа и регистрации перенесены на модальные окна, которые раскрываются при нажатии на соответствующие кнопки.
