### ISSUE TITLE
File Naming

### ISSUE THREAD

**Issue by iatsdotfatr** [hoka-hoka/task_1#5]
![hyph](https://user-images.githubusercontent.com/51824674/92102166-0cc6fe80-ee00-11ea-9c72-9ad685cb0673.png)
![Screenshot from 2020-09-03 16-10-07](https://user-images.githubusercontent.com/51824674/92102171-0f295880-ee00-11ea-81b6-ba81fa7ccfdc.png)

**Comment by hoka-hoka** [comment]
Подгружаются из библиотеки шрифтов Google Fonts. Папку с локальными шрифтами удалил.
