### ISSUE TITLE
File Naming

### ISSUE THREAD

**Issue by iatsdotfatr** [hoka-hoka/task_1#7]
Не надо закрывать issues, просто отмечай, что исправил).

Шрифты надо подключать вручную, прямое требование на риззоме
![Screenshot from 2020-09-10 18-57-17](https://user-images.githubusercontent.com/51824674/92732443-4a93cc00-f398-11ea-8394-b011dc0ec9a5.png)

**Comment by hoka-hoka** [comment]
Подключил.

**Comment by iatsdotfatr** [comment]
Картинки тоже должны быть lowercase-hyphenated
![pictures-lower-case-hyphen](https://user-images.githubusercontent.com/51824674/97172005-9075e980-17b8-11eb-8b73-461b5a947370.png)

**Comment by hoka-hoka** [comment]
Наверное, использовать числа в названии не совсем правильно, но эти картинки всё-равно идут только в качестве заполнителя. Исправил.
