### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by iatsdotfatr** [hoka-hoka/task_1#8]
1. Добавить команду для клонирования репозитория.
2. В демо добавить ui-kit, он должен быть pixel perfect, responsive можно не делать.
3. Регистрация/вход согласно макету являются отдельными страницами со своим фоном.

**Comment by hoka-hoka** [comment]
Привет, у меня сейчас совсем немного свободного времени, поэтому я не могу часто делать коммиты. Из-за того, что требуется вёрстка и ui-kit мне приходится делить код на более мелкие компоненты. Я постараюсь ускориться.

**Comment by hoka-hoka** [comment]
Если у меня есть вопросы по поводу правок, которые мне приходят, где мне их задавать?

**Comment by iatsdotfatr** [comment]
Можешь здесь, можешь в телегу @thunderleg.

**Comment by hoka-hoka** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
Названия ссылок надо поправить
![links naming](https://user-images.githubusercontent.com/51824674/97172074-ad122180-17b8-11eb-8840-c473f46795ce.png)

**Comment by hoka-hoka** [comment]
Поправил.
